version: '3.8'

services:
  # 1. База даних для Бронювань
  postgres-db:
    image: postgres:15-alpine
    container_name: booking_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. База даних для Аналітики
  mongo-db:
    image: mongo:latest
    container_name: analytics_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 3. Брокер повідомлень
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: event_broker
    restart: always
    ports:
      - "5672:5672"   # Порт для підключення
      - "15672:15672" # Веб-інтерфейс (http://localhost:15672)

  # 4. Кеш
  redis:
    image: redis:7-alpine
    container_name: app_cache
    restart: always
    ports:
      - "6379:6379"

# Створюємо "іменовані" томи, щоб дані не зникали при перезапуску
volumes:
  postgres_data:
  mongo_data: